repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
