repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
