---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-oauth2_proxy-default-debian-stretch
    image: bitnami/python:3.6-debian-9
    pre_build_image: true
  - name: molecule-oauth2_proxy-default-debian-buster
    image: bitnami/python:3.6-debian-10
    pre_build_image: true
  - name: molecule-oauth2_proxy-default-centos7
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: molecule-oauth2_proxy-default-centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
