---
- hosts: all
  tasks:
    - name: Install python3-apt for the Debian releases
      shell: apt-get update && apt-get -y install python-apt
      args:
        warn: false
      when:
        - "ansible_distribution|lower in ['debian']"

    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Ensure sudo is installed, both for Ansible and for the services script(s)
      package:
        name:
          - sudo
        state: present
