---
- hosts: all
  tasks:
    - name: Install python3-apt for the Debian releases
      shell: apt-get update && apt-get -y install python-apt sudo
      args:
        warn: false
      when:
        - "ansible_distribution|lower in ['debian', 'ubuntu']"

    - name: Gather package facts
      package_facts:
        manager: auto
      when:
        - "ansible_distribution|lower not in ['debian', 'ubuntu']"

    - name: Ensure sudo is installed, both for Ansible and for the services script(s)
      package:
        name:
          - sudo
        state: present
      when:
        - "ansible_distribution|lower not in ['debian', 'ubuntu']"
